[workspace]
members = ["core", "backend", "plugin"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[patch.'https://github.com/hypengw/QcmBackend.git']
qcm-core = { path = "./core" }

[profile.release]
lto = "fat"
strip = "debuginfo"
codegen-units = 1
panic = "abort"
