[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
qcm-core = {path = "../../core"}
log = "0.4"
async-std = { version = "1", features = ["attributes", "tokio1"] }

[dependencies.sea-orm-migration]
version = "1.1"
features = ["sqlx-sqlite", "runtime-tokio", "with-uuid", "with-chrono"]
